version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 15

    groups:
      express:
        patterns:
          - 'express'
          - 'express-*'
          - 'cookie-parser'

      jest:
        patterns:
          - 'jest'
          - 'jest-*'
          - 'eslint-plugin-jest'

    schedule:
      interval: monthly
      time: '10:30'
      timezone: 'Europe/London'

    cooldown:
      default-days: 7

    versioning-strategy: increase

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    schedule:
      interval: monthly
      time: '10:30'
      timezone: 'Europe/London'

    cooldown:
      default-days: 7