#!/bin/sh

mkdir -p tmp/performance-testing
cd tmp/performance-testing
rm -Rf govuk-prototype-kit-performance-kit 
git clone git@github.com:alphagov/govuk-prototype-kit-performance-kit.git
cd govuk-prototype-kit-performance-kit
echo '{"collectUsageData": false}' > usage-data-config.json
npm install
if [ -n "$1" ]; then
  npm install $1
else
  tar -czpf kit-dependency.tar.gz --exclude="tmp" ../..
  npm install kit-dependency.tar.gz
fi
npm run dev
