#!/bin/sh

rm -Rf tmp/performance-testing
mkdir -p tmp/performance-testing
if [ -n "$1" ]; then
  dependency=$1
else
  echo "We don't yet support running against your local version.  Please run against a branch or release."
  echo "e.g."
  echo "$0 13.0.0"
  echo "$0 alphagov/govuk-prototype-kit#main"
  
  exit 1
#  tar -cpf tmp/performance-testing/kit-dependency.tar --exclude="tmp" .
#  dependency="kit-dependency.tar"
fi
cd tmp/performance-testing
rm -Rf nowprototypeit-performance-kit 
git clone git@github.com:alphagov/nowprototypeit-performance-kit.git
cd nowprototypeit-performance-kit
echo '{"collectUsageData": false}' > usage-data-config.json
npm install $dependency --save-exact
npm install
npm run dev
