#!/bin/sh

mkdir -p ~/projects/prototype-kits/ && rm -Rf ~/projects/prototype-kits/now-prototype-it-govuk-companion && ./bin/cli create --version=local-symlink ~/projects/prototype-kits/now-prototype-it-govuk-companion --use-njk-extensions
