#!/bin/sh

mkdir -p ~/projects/prototype-kits/ && rm -Rf ~/projects/prototype-kits/companion-prototype-kit && ./bin/cli create --version=local ~/projects/prototype-kits/companion-prototype-kit --use-njk-extensions
rm -Rf ~/projects/prototype-kits/companion-prototype-kit/node_modules/govuk-prototype-kit
ln -s $(pwd) ~/projects/prototype-kits/companion-prototype-kit/node_modules/govuk-prototype-kit
echo '{"collectUsageData": false}' > ~/projects/prototype-kits/companion-prototype-kit/usage-data-config.json
