name: Validate

on:
  push:
    branches:
      - main
      - support/*
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: npm ci

      - run: ./bin/cli validate-plugin validate-plugin
