name: Validate

on:
  push:
    branches:
      - main
      - support/*
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - run: npm ci

      - run: npx . validate-plugin
